application:
  yml:
spring:
  application:
    name: wfm
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      #      ddl-auto: validate
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    locations: classpath:db/migration
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

# JWT Configuration
jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds

# Logging
logging:
  level:
    com.mazen.wfm: DEBUG
    org.springframework.security: DEBUG

